- hosts: localhost
  become: true
  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present
        
    - name: Setting the http server page for apache
      shell: echo "<h1>Cloudyeti Tutorial for ansible with Systems Manager</h1>" > /var/www/html/index.html
      
    - name: Starting the service
      service:
        name: httpd
        state: started
